### PR TITLE
The gradle script was not working, and I use eclipse anyway, so i added the eclipse stuff. 

### PR DESCRIPTION
**Pull request by madhephaestus**
This is the first step in turning this into an eclipse plugin extension to the Java plugin. Eclipse brings in methods prediction, bracket tracing, and live syntax checking. 

I also want to add VR style inputs and visual debug tracing. 

If this is not the direction you want to go with this, let me know and ill stay in my fork.

### CODE REVIEW

**Comment by miho** [comment]
Hi,

thanks for contributing to JFXScad! I definitely like your ideas! You should contribute to the upstream version.

**Flow visualization:** Please share your ideas about visual debugging. If you like you could also contribute to our visual programming environment. Here's an example of the current JCSG plugin:

jcsg-01
jcsg-02

**About the project structure:** I added the `eclipse` and `idea` tasks to the gradle scripts. This should allow you to use the project from eclipse. I just tried it with a fresh Luna installation. I don't like the idea of having multiple dependency definitions since they are likely getting out of sync over time. Please let me know if that works for you.

Michael

**Comment by madhephaestus** [comment]
Wow! that looks awesome, where can i find the sources for this so i can contribute?

**Comment by miho** [comment]
You can start here: http://vrl-studio.mihosoft.eu/

**Comment by miho** [comment]
The developer forum: https://groups.google.com/forum/#!forum/vrl-developers

**Pull request closed without merging**
